### PR TITLE
tap: Add new test suite for `tap` command

### PR DESCRIPTION
**Pull request by mayankshah1607**
This PR adds the following tests for `tap` command:

- `tap` can tap deployment
- `tap` can use context namespace
- `tap` can tap pod
- `tap` errors on disabled deployment
- `tap` can tap service calls
- `tap` can filter using method
- `tap` can filter using authority

`tap` test can be muted by setting `testCase.tap.skip` to `true`. By setting `testCase.tap.clean` to `true`, the tests shall delete the sample application created for testing.

### CODE REVIEW

**Review by Pothulapati — COMMENTED** [review]
Overall the code looks good. 
_( +1 on the re-use of code from `linkerd2`)_

but my run actually failed on kind, implying
```
  tap:
  can tap a deployment using context namespace
  /conformance/specs/tap/specs.go:16

• Failure [0.070 seconds]

/conformance/specs/specs.go:60

  /conformance/specs/specs.go:39
    tap:
    /conformance/specs/tap/specs.go:9
      can tap a deployment using context namespace [It]
      /conformance/specs/tap/specs.go:16

      failed to set context: error: no current context is set

      Expected
          <*exec.ExitError | 0xc00042d600>: {
              ProcessState: {
                  pid: 513,
                  status: 256,
                  rusage: {
                      Utime: {Sec: 0, Usec: 63391},
                      Stime: {Sec: 0, Usec: 27167},
                      Maxrss: 41956,
                      Ixrss: 0,
                      Idrss: 0,
                      Isrss: 0,
                      Minflt: 3125,
                      Majflt: 1,
                      Nswap: 0,
                      Inblock: 256,
                      Oublock: 0,
                      Msgsnd: 0,
                      Msgrcv: 0,
                      Nsignals: 0,
                      Nvcsw: 293,
                      Nivcsw: 15,
                  },
              },
              Stderr: nil,
          }
      to be nil

      /conformance/specs/tap/tests.go:94
```
Also, I don't understand why setting kubectl context is important and a thing to test? :thinking:

**Comment by mayankshah1607** [comment]
@Pothulapati 
Hmm, I've replicated the test cases from the integration tests, and this happened to be one of them - https://github.com/linkerd/linkerd2/blob/main/test/integration/tap/tap_test.go#L115

Even I wasn't too sure why we need to test `tap` using context namespace, but added a test anyway in case it would be desirable later on. It would make sense why this may not be relevant to conformance tests because we can expect users to not have any current context set while running the tests.

**Comment by Pothulapati** [comment]
@mayankshah1607 Tried running this once again, and it failed once again!

```
  tap:
  creating sample application
  /conformance/specs/tap/specs.go:14

• Failure [0.037 seconds]

/conformance/specs/specs.go:60

  /conformance/specs/specs.go:39
    tap:
    /conformance/specs/tap/specs.go:9
      creating sample application [It]
      /conformance/specs/tap/specs.go:14

      `inject` command failed: Cannot find Linkerd: configmaps "linkerd-config" not found
      Validate the install with: linkerd check --linkerd-namespace l5d-conformance

      Expected
          <*exec.ExitError | 0xc0002b6140>: {
              ProcessState: {
                  pid: 341,
                  status: 256,
                  rusage: {
                      Utime: {Sec: 0, Usec: 38128},
                      Stime: {Sec: 0, Usec: 12709},
                      Maxrss: 35948,
                      Ixrss: 0,
                      Idrss: 0,
                      Isrss: 0,
                      Minflt: 2818,
                      Majflt: 0,
                      Nswap: 0,
                      Inblock: 0,
                      Oublock: 0,
                      Msgsnd: 0,
                      Msgrcv: 0,
                      Nsignals: 0,
                      Nvcsw: 393,
                      Nivcsw: 6,
                  },
              },
              Stderr: nil,
          }
      to be nil

      /conformance/specs/tap/tests.go:60
------------------------------
  tap:
  can tap a deployment
  /conformance/specs/tap/specs.go:15

• Failure [60.502 seconds]

/conformance/specs/specs.go:60

  /conformance/specs/specs.go:39
    tap:
    /conformance/specs/tap/specs.go:9
      can tap a deployment [It]
      /conformance/specs/tap/specs.go:15

      tap failed: cmd [/root/.linkerd2/bin/linkerd --linkerd-namespace l5d-conformance --context= tap deploy/t1 --namespace ] Timed out trying to read 10 lines
      Expected
          <*errors.errorString | 0xc000969270>: {
              s: "cmd [/root/.linkerd2/bin/linkerd --linkerd-namespace l5d-conformance --context= tap deploy/t1 --namespace ] Timed out trying to read 10 lines",
          }
      to be nil

      /conformance/specs/tap/tests.go:84
------------------------------
  tap:
  cannot tap a disabled deployment
  /conformance/specs/tap/specs.go:16

• Failure [0.060 seconds]

/conformance/specs/specs.go:60

  /conformance/specs/specs.go:39
    tap:
    /conformance/specs/tap/specs.go:9
      cannot tap a disabled deployment [It]
      /conformance/specs/tap/specs.go:16

      expected [Error: all pods found for deployment/t4 have tapping disabled], got [Error: HTTP error, status Code [404] (unexpected API response: 404 page not found]
      Expected
          <string>: "...ror: HTTP e..."
      to equal               |
          <string>: "...ror: all po..."

      /conformance/specs/tap/tests.go:101
------------------------------
  tap:
  can tap a service call
  /conformance/specs/tap/specs.go:17

• Failure [60.502 seconds]

/conformance/specs/specs.go:60

  /conformance/specs/specs.go:39
    tap:
    /conformance/specs/tap/specs.go:9
      can tap a service call [It]
      /conformance/specs/tap/specs.go:17

      failed to tap service call
      Expected
          <*errors.errorString | 0xc000220060>: {
              s: "cmd [/root/.linkerd2/bin/linkerd --linkerd-namespace l5d-conformance --context= tap deploy/gateway --to svc/t2-svc --namespace ] Timed out trying to read 10 lines",
          }
      to be nil

      /conformance/specs/tap/tests.go:108
------------------------------
  tap:
  can tap a pod
  /conformance/specs/tap/specs.go:18

• Failure [0.001 seconds]

/conformance/specs/specs.go:60

  /conformance/specs/specs.go:39
    tap:
    /conformance/specs/tap/specs.go:9
      can tap a pod [It]
      /conformance/specs/tap/specs.go:18

      failed to get pods for deploy/t3
      Expected
          <*errors.errorString | 0xc000221a20>: {
              s: "an empty namespace may not be set when a resource name is provided",
          }
      to be nil

      /conformance/specs/tap/tests.go:118
------------------------------
  tap:
  can filter tap events by method
  /conformance/specs/tap/specs.go:19

• Failure [60.502 seconds]

/conformance/specs/specs.go:60

  /conformance/specs/specs.go:39
    tap:
    /conformance/specs/tap/specs.go:9
      can filter tap events by method [It]
      /conformance/specs/tap/specs.go:19

      error filtering events by method: cmd [/root/.linkerd2/bin/linkerd --linkerd-namespace l5d-conformance --context= tap deploy/gateway --namespace  --method GET] Timed out trying to read 10 lines
      Expected
          <*errors.errorString | 0xc000176020>: {
              s: "cmd [/root/.linkerd2/bin/linkerd --linkerd-namespace l5d-conformance --context= tap deploy/gateway --namespace  --method GET] Timed out trying to read 10 lines",
          }
      to be nil

      /conformance/specs/tap/tests.go:133
------------------------------
  tap:
  can filter tap events by authority
  /conformance/specs/tap/specs.go:20
```

**Comment by mayankshah1607** [comment]
@Pothulapati That's strange. The tests always showed success for me. Can you share your config.yaml so I can debug whats causing this failure?

**Comment by ihcsim** [comment]
Are the errors, by any chance, related to your kubeconfig file, similar to https://github.com/linkerd/linkerd2/issues/4818?

**Review by ihcsim — APPROVED** [review]
LGTM.

**Review by Pothulapati — APPROVED** [review]
LGTM!
```
{"name":"  tap: creating sample application","status":"passed","meta":{"path":"linkerd2-conformance|report.xml|Linkerd2 conformance tests"}}
{"name":"  tap: can tap a deployment","status":"passed","meta":{"path":"linkerd2-conformance|report.xml|Linkerd2 conformance tests"}}
{"name":"  tap: cannot tap a disabled deployment","status":"passed","meta":{"path":"linkerd2-conformance|report.xml|Linkerd2 conformance tests"}}
{"name":"  tap: can tap a service call","status":"passed","meta":{"path":"linkerd2-conformance|report.xml|Linkerd2 conformance tests"}}
{"name":"  tap: can tap a pod","status":"passed","meta":{"path":"linkerd2-conformance|report.xml|Linkerd2 conformance tests"}}
{"name":"  tap: can filter tap events by method","status":"passed","meta":{"path":"linkerd2-conformance|report.xml|Linkerd2 conformance tests"}}
{"name":"  tap: can filter tap events by authority","status":"passed","meta":{"path":"linkerd2-conformance|report.xml|Linkerd2 conformance tests"}}
```

**Pull request merged**
